### ISSUE TITLE
FAQ button

### ISSUE THREAD

**Issue by evermake** [one-zero-eight/sport-bot#11]
### Describe the feature

Add "FAQ" link-button to the updated sports FAQ.

### Suggested solution

Create a post in telegra.ph with updated information about sport and add link to this page in main menu.

**Comment by asqarslanov** [comment]
I've prepared a draft of what the FAQ page may look like. The screenshots now are just for demonstration purposes, they need to be improved in the future. The overall structure seems pretty fine to me.

https://telegra.ph/INH-Sport-Bot-FAQ-09-28

**Comment by evermake** [comment]
@asqarslanov, thanks for creating the post.

I've added the button and closed this issue, though initially I wanted to create an article to replace the FAQ on the website:

![image](https://github.com/user-attachments/assets/44a7ca3d-1c0d-45ec-b333-ec838d485354)

not to create FAQ about the bot.

I wanted to modify your post, improve screenshots and add a section from the website, but I don't have time for this right now. Moreover, since [Durov's post](https://t.me/durov/343) Telegraph does not allow to upload media, and we either need to host images somewhere or move the article to another place. I don't have time for this either.
