### ISSUE TITLE
Sport calendar export button

### ISSUE THREAD

**Issue by evermake** [one-zero-eight/sport-bot#16]
Since we have an access to Sport API, we can, finally, let users to subscribe to the calendar of their sport classes. After implementing this functionality on backend (in Events service?) we need also to add the button that links to the user's calendar in the bot.

**Comment by evermake** [comment]
@dantetemplar, will you make it on the backend?

**Comment by ArtemSBulgakov** [comment]
https://github.com/one-zero-eight/InNoHassle-Events/issues/57

**Comment by dantetemplar** [comment]
> @dantetemplar, will you make it on the backend?

I will...
